# --------------------------------------------
# Configuração do Ruff
# --------------------------------------------

# Compatível com Black
line-length = 88
target-version = "py311"

# Ignorar diretórios comuns
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    ".env",
    ".mypy_cache",
    "build",
    "dist",
    "__pypackages__",
    "docs/_build",
    "node_modules",
]

# Regras habilitadas (inclui verificação de complexidade C90)
select = ["E", "F", "W", "B", "I", "D", "S", "C90"]

# Ignorar regras que conflitam com o Black
ignore = ["E203"]

# Ignorar avisos específicos por arquivo
[per-file-ignores]
"tests/*" = ["D", "S101"]
"__init__.py" = ["F401"]
